services:
  db:
    container_name: db
    image: ghcr.io/tursodatabase/libsql-server:latest
    environment:
      - SQLD_NODE=primary
    volumes:
      - db_data:/var/lib/sqld
    ports:
      - 8080:8080
      - 5001:5001

volumes:
  db_data: